# Generated by Django 2.2.5 on 2020-03-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search1',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
