# Generated by Django 2.2.5 on 2020-03-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200323_2059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search1',
            new_name='Search',
        ),
    ]
